server:
  port: 8081
  servlet:
    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-app
          jwk-set-uri: http://localhost:8080/realms/spring-app/protocol/openid-connect/certs
